<?php

$jsonResponse = '{
    "_id": "1eda642a-a9a3-457c-99af-3bc5e8d5c4c9",
    "login": "50194988",
    "name": "mt5a",
    "server": "ICMarketsSC-Demo",
    "magic": 123456,
    "connectionStatus": "DISCONNECTED",
    "state": "DEPLOYED",
    "type": "cloud-g2",
    "accessToken": "VreIBlCEmqngArxSIZKBcuoC7tA0RXsOh4FCiwFaQ5dzo4v8HfWJFP2Opr1MSxC3",
    "region": "vint-hill",
    "manualTrades": true,
    "quoteStreamingIntervalInSeconds": 2.5,
    "tags": [],
    "reliability": "high",
    "baseCurrency": "USD",
    "copyFactoryRoles": ["PROVIDER"],
    "resourceSlots": 1,
    "copyFactoryResourceSlots": 4,
    "version": 4,
    "hash": 18093,
    "primaryReplica": true,
    "userId": "7b17e36a88502fd2faae5dd9d2166873",
    "accountReplicas": [],
    "metastatsHourlyTarificationEnabled": false,
    "riskManagementApiEnabled": false,
    "createdAt": "2022-12-11T09:09:27.454Z"
  }';

$arrayResonse = [
    '_id'                             => '1eda642a-a9a3-457c-99af-3bc5e8d5c4c9',
    'login'                           => '50194988',
    'name'                            => 'mt5a',
    'server'                          => 'ICMarketsSC-Demo',
    'magic'                           => 123456,
    'connectionStatus'                => 'DISCONNECTED',
    'state'                           => 'DEPLOYED',
    'type'                            => 'cloud-g2',
    'accessToken'                     => 'VreIBlCEmqngArxSIZKBcuoC7tA0RXsOh4FCiwFaQ5dzo4v8HfWJFP2Opr1MSxC3',
    'region'                          => 'vint-hill',
    'manualTrades'                    => true,
    'quoteStreamingIntervalInSeconds' => 2.5,
    'tags'                            => [],
    'reliability'                     => 'high',
    'baseCurrency'                    => 'USD',
    'copyFactoryRoles'                => [
        'PROVIDER',
    ],
    'resourceSlots'                      => 1,
    'copyFactoryResourceSlots'           => 4,
    'version'                            => 4,
    'hash'                               => 18093,
    'primaryReplica'                     => true,
    'userId'                             => '7b17e36a88502fd2faae5dd9d2166873',
    'accountReplicas'                    => [],
    'metastatsHourlyTarificationEnabled' => false,
    'riskManagementApiEnabled'           => false,
    'createdAt'                          => '2022-12-11T09:09:27.454Z',
];
